# Generated by Django 4.0.3 on 2022-03-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_order_total_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
