# Generated by Django 4.0.3 on 2022-03-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
    ]
