# Generated by Django 4.0.3 on 2022-03-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_category_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
