# Generated by Django 4.0.3 on 2022-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_invoices_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='invoices',
            name='temp_id_2',
            field=models.IntegerField(null=True),
        ),
    ]
